# Alias config; prefer using `uelm4.config.load_config("base16k")`.
model:
  d: 2048
  vocab_size: 32000
  band: 256
  tied_readout: true
memory:
  type: "table"
  K: 131072
  shortlist_k: 32
solver:
  T_train: 2
  T_infer: 1
  rho: 1.0
  beta_start: 0.5
  beta_end: 1.5
  early_exit_tol: 1.0e-3
field:
  spectral_norm: true
